### ISSUE TITLE
Absolute paths instead of relative paths (mwixnet.yml)

### ISSUE THREAD

**Issue by davidtavarez** [mimblewimble/mwixnet#12]
It would be nice if relative paths are used instead of using relative paths like here: 
https://github.com/mimblewimble/mwixnet/blob/f4c6e91eb4b0f43edfc761a31759880260f05354/src/main.rs#L33

**Comment by scilio** [comment]
`../mwixnet.yml` is pointing to [mwixnet.yml](https://github.com/mimblewimble/mwixnet/blob/main/mwixnet.yml). It's a compile-time reference, not a runtime one. Using relative paths is the correct approach.
