### ISSUE TITLE
Generate random pubkey for each payload

### ISSUE THREAD

**Issue by scilio** [mimblewimble/mwixnet#19]
The minimal space efficiency gains fail to justify the additional complexity of our current scheme. 
https://github.com/mimblewimble/mwixnet/pull/18#discussion_r1069533122

**Comment by phyro** [comment]
This will also require updating the README.md file with this simplified scheme. Also, it would be nice to include the full definition of each payload P_i and each onion layer in README.md where the last layer would equate the data we send in json.
